
from PIL import ImageTk, Image

def leer_imagen( path, size): 
        return ImageTk.PhotoImage(Image.open(path).resize(size, Image.ANTIALIAS)) 



name_lesson = {

    
'802': ['M1L1. Introducción a Scratch. El primer proyecto.', 
        'M1L2. Movimiento de los sprites en Scratch', 
        'M1L3. Editor de imágenes mágico', 
        'M1L4. ¿Qué es un bug? Debuggeo de programas', 
        'M1L5. ¡Koddich!', 'M2L1. ¡Eventos en Scratch!', 
        'M2L2. Fundamentos de la animación de sprites', 
        'M2L3. ¡Mi banda de música mágica!', 
        'M2L4. Koddich 2.0', 
        'M3L1. ¡Entendiendo los videojuegos!', 
        'M3L2. Bloques personalizados: Por qué y cómo crearlos', 
        'M3L3. Diseño de objetivos en un videojuego', 
        'M3L4. ¡Videojuegos del género RPG!', 
        'M3L5. Own character', 
        'M3L6. Games debug!', 
        'M3L7. Koddich!', 
        'M4L1. Mecánicas de juego: ¡Los ingredientes para un videojuego increíble!', 
        'M4L2. Puntaje y variables', 
        'M4L3. ¡Hora del desafío!', 
        'M4L4. Clones!', 
        'M4L5. Scrolling!', 
        'M4L6. Games debugging!', 
        'M4L7. Koddich! Game season!'
        ],

'663': ['M1.L1 Introducción',
         'M1.L2 Algoritmos',
         'M1.L3 Graficos',
         'M1.L4 El Juego',
         'M2.L1 El primer juego en Scratch',
         'M2.L2 Coordenadas',
         'M2.L3 Condiciones',
         'M2.L4 Números aleatorios',
         'M3.L1 Disfraces',
         'M3.L2 ¡Más variables!',
         'M3.L3 Trabajando con bucles infinitos',
         'M3.L4 Mensajes',
         'M4.L1 Pixilart',
         'M4.L2 Operadores lógicos',
         'M4.L3 Tu propio proyecto',
         'M4.L4 Presentación',
         'M5.L1 Bloque "Preguntar y esperar"',
         'M5.L2 Mensajes ramificados',
         'M5.L3 La búsqueda',
         'M5.L4 Texto-a-voz',
         'M6.L1 Flappy Bird',
         'M6.L2 Creación de música',
         'M6.L3 Spawn aleatorio',
         'M6.L4 Among Us',
         'M7.L1 Desplazarse',
         'M7.L2 Desplazamiento horizontal',
         'M7.L3 Desplazamiento con varios sprites',
         'M7.L4 Revision',
         'M8.L1 Idea y plan',
         'M8.L2 Trabajando en el proyecto',
         'M8.L3 Pruebas y depuración', 
         'M8.L4 Presentación del proyecto'],

'714': ['M1.L1 La tortuga',
        'M1.L2 Variables, tipos de datos y operaciones con ellas.',
        'M1.L3 Entrada de texto y números',
        'M1.L4 Proyectos individuales',
        'M2.L1 Sentencias condicionales',
        'M2.L2 Combinación de condiciones',
        'M2.L3 Bucles infinitos',
        'M2.L4 Piedra, papel o tijera',
        'M3.L1 Bucles FOR',
        'M3.L2 Sentencias condicionales dentro de un bucle FOR',
        'M3.L3 Interfiriendo un bucle',
        'M3.L4 El juego Carrera de Tortugas',
        'M4.L1 Listas',
        'M4.L2 Diccionario',
        'M4.L3 Diccionarios, Proyecto',
        'M4.L4 Funciones',
        'M5.L1 Pygame zero: Conociendo',
        'M5.L2 Teclado y animaciones',
        'M5.L3 Colliderect y salida de texto',
        'M5.L4 Creación de funciones',
        'M6.L1 Movimiento del ratón',
        'M6.L2 Procesamiento del clic',
        'M6.L3 Desarrollo del clicker',
        'M6.L4 Clicker: compra de skins',
        'M7.L1 Juego-roguelike',
        'M7.L2 Método Colledelist',
        'M7.L3 Preparación para el trabajo',
        'M7.L4 Introducción de las funciones',
        'M8.L1 Trabajando en los enemigos',
        'M8.L2 Nuevos niveles', 
        'M8.L3 Modificación del juego', 
        'M8.L4 Graduación'],

'847': ['М1.L1 Introducción',
        'М1.L2 Cambios de paisaje',
        'М1.L3 Creación de modelos 3D',
        'М1.L4 Conceptos basicos de programacion',
        'М2.L1 Torre del Infierno. Funciones',
        'М2.L2 Torre del Infierno. Declaraciones condicionales',
        'М2.L3 Torre del Infierno. Hinge y Clic Detector',
        'М2.L4 Torre del Infierno. Animaciones',
        'М3.L1 Pista de carreras',
        'М3.L2 ¡Construyendo un auto personalizado!',
        'М3.L3 Efectos para el coche',
        'М3.L4 Check Puntos y la línea de meta',
        'М4.L1 Desarrollo de equipo',
        'М4.L2 Moneda del juego. Mejoras',
        'М4.L3 Creating Tools',
        'М4.L4 Currency exchange office. Bubble Chat',
        'М5.L1 Introduction to the Detective Genre',
        'М5.L2 Level Design',
        'М5.L3 Creating a sword. Applying Speed Boost',
        'М5.L4 Events in Roblox',
        'М6.L1 Fundamentals of programming. Cycles',
        'М6.L2 Cloning objects. Selecting roles',
        'М6.L3 Teleporting Players'
        'М6.L4',
        'М7.L1',
        'М7.L2',
        'М7.L3',
        'М7.L4',
        'М8.L1',
        'М8.L2',
        'М8.L3',
        'М8.L4',
        ]
}

